### ISSUE TITLE
使用提供的 docker 镜像报错

### ISSUE THREAD

**Issue by allanpk716** [std4453/mikanarr#1]
docker-compose 如下：

```
version: "3"

services:
  mikanarr:
    image: std4453/mikanarr
    ports:
      - "12306:12306"
    volumes:
      - /xx/xx/mikanarr/data:/usr/src/app/data
    environment:
      TZ: Asia/Shanghai
      SONARR_API_KEY: 1234567890
      SONARR_API_ROOT: http://192.168.50.252:8989/api
    restart: unless-stopped
```

报错如下：
```
,yarn run v1.22.5,
$ dotenv node server/index.js,
/usr/src/app/node_modules/http-proxy-middleware/dist/config-factory.js:38,
        throw new Error(errors_1.ERRORS.ERR_CONFIG_FACTORY_TARGET_MISSING);,
    at Object.createConfig (/usr/src/app/node_modules/http-proxy-middleware/dist/config-factory.js:38:15),
Error: [HPM] Missing "target" option. Example: {target: "http://www.example.org"},
^,
    at Module.load (internal/modules/cjs/loader.js:928:32),
    at new HttpProxyMiddleware (/usr/src/app/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:147:40),
    at createProxyMiddleware (/usr/src/app/node_modules/http-proxy-middleware/dist/index.js:16:28),
    at Object.<anonymous> (/usr/src/app/server/index.js:94:3),
    at Module._compile (internal/modules/cjs/loader.js:1063:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10),
    at Function.Module._load (internal/modules/cjs/loader.js:769:14),
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12),
    at internal/main/run_main_module.js:17:47,
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
