### ISSUE TITLE
使用使用nginx二级路径的sonarr地址会报错504[ENOTFOUND]

### ISSUE THREAD

**Issue by lurenjiamax** [std4453/mikanarr#15]
如题
.env文件:
```
SONARR_API_KEY=key
SONARR_HOST:http://xxx/sonarr
```
docker-compose.yml:
```
version: "3"

services:
  mikanarr:
    container_name: mikanarr
    image: std4453/mikanarr
    volumes:
      - ~/docker/mikanarr/data:/usr/src/app/data
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - http_proxy=http://192.168.123.101:7890
      - https_proxy=http://192.168.123.101:7890
    ports:
      - 12306:12306
    restart: unless-stopped 
```
报错日志:
```
mikanarr  | GET /api/patterns/1 304 6.755 ms - -
mikanarr  | [HPM] Error occurred while proxying request xxx:12306/api/series?apikey=key to http://xxx/sonarr [ENOTFOUND](https://nodejs.org/api/errors.html#errors_common_system_errors)
mikanarr  | GET /sonarr/series 504 353.388 ms - -
```
nginx:

```
  location /sonarr {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_pass              http://localhost:8989/sonarr;
```
